"use client";

import { useState } from "react";
import { BASESCAN_URL } from "@/lib/config";

interface FAQItem {
  q: string;
  a: React.ReactNode;
}

const AUDIT_URL = "https://www.yo.xyz/files/Yo-Protocol-Hunter-Security-Audit-Report.pdf";

const ITEMS: FAQItem[] = [
  {
    q: "Is it safe and transparent?",
    a: (
      <div className="space-y-3 text-sm" style={{ color: "var(--color-n-muted)" }}>
        <p>
          Yes. Notherc is fully non-custodial — your funds are held exclusively by audited
          ERC-4626 smart contracts deployed on Base, not by Notherc or any intermediary.
          No company can freeze, move, or access your assets.
        </p>
        <p>
          Every deposit and withdrawal is publicly verifiable on{" "}
          <a
            href={BASESCAN_URL}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "var(--color-n-accent)", textDecoration: "underline" }}
          >
            BaseScan
          </a>
          . The vault contract addresses are shown on every position card so you can
          independently verify at any time.
        </p>
      </div>
    ),
  },
  {
    q: "Who holds my funds?",
    a: (
      <p className="text-sm" style={{ color: "var(--color-n-muted)" }}>
        No one. Your funds are held by an ERC-4626 smart contract on Base — not by Notherc,
        not by YO Protocol, not by any company. Only you can redeem your shares.
        Notherc is a front-end interface only and has zero administrative access to the contracts.
      </p>
    ),
  },
  {
    q: "Where does the yield come from?",
    a: (
      <div className="space-y-3 text-sm" style={{ color: "var(--color-n-muted)" }}>
        <p>
          Yield is generated by YO Protocol, which deploys deposited assets into battle-tested
          on-chain strategies — primarily lending markets and liquidity pools on Base
          (e.g. Aave, Compound, and similar protocols).
        </p>
        <p>
          Assets are constantly rebalanced between strategies to capture the best available rate.
          All activity is verifiable on-chain. There are no off-chain or custodial components
          involved in yield generation.
        </p>
      </div>
    ),
  },
  {
    q: "What are the risks?",
    a: (
      <div className="space-y-2 text-sm" style={{ color: "var(--color-n-muted)" }}>
        <p>All yield-bearing products carry risk. Key risks include:</p>
        <ul className="space-y-1 pl-4">
          <li>
            <span style={{ color: "var(--color-n-text)" }}>Smart contract risk —</span>{" "}
            bugs in contract code, however unlikely with audited ERC-4626 vaults.
          </li>
          <li>
            <span style={{ color: "var(--color-n-text)" }}>Variable APY —</span>{" "}
            yield rates change based on DeFi market conditions and cannot be guaranteed.
          </li>
          <li>
            <span style={{ color: "var(--color-n-text)" }}>Asset price risk —</span>{" "}
            ETH and BTC vaults are subject to market price movements.
          </li>
        </ul>
        <p>yoUSD carries the lowest risk as a stablecoin with no price exposure.</p>
      </div>
    ),
  },
  {
    q: "Can I withdraw at any time?",
    a: (
      <p className="text-sm" style={{ color: "var(--color-n-muted)" }}>
        Yes, with no lock-up period. Most withdrawals are instant. In high-demand periods,
        a small number may be queued and processed within 24 hours by the YO Protocol vault.
        You will always be informed which type of withdrawal applies before you confirm.
      </p>
    ),
  },
  {
    q: "Is the APY guaranteed?",
    a: (
      <p className="text-sm" style={{ color: "var(--color-n-muted)" }}>
        No. APY is variable and changes based on DeFi market conditions — supply, demand,
        and strategy performance. The rate shown is the trailing 7-day average, updated
        continuously. Historical APY is not a guarantee of future returns.
      </p>
    ),
  },
  {
    q: "Does Notherc take a fee?",
    a: (
      <div className="space-y-3 text-sm" style={{ color: "var(--color-n-muted)" }}>
        <p>
          Notherc itself charges{" "}
          <span style={{ color: "var(--color-n-text)" }}>no deposit or withdrawal fees</span>.
          No cut from your yield, no subscription fees.
        </p>
        <p>
          YO Protocol may apply a small performance fee on vault yield — this is already
          reflected in the APY shown. The only other cost is Base network gas, typically
          less than $0.01 per transaction.
        </p>
      </div>
    ),
  },
  {
    q: "Are the contracts audited?",
    a: (
      <div className="space-y-3 text-sm" style={{ color: "var(--color-n-muted)" }}>
        <p>
          Yes. YO Protocol smart contracts have been independently audited by Hunter Security.
          Notherc is a front-end interface — it holds no funds and has no admin keys.
        </p>
        <a
          href={AUDIT_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 text-xs font-semibold"
          style={{ color: "var(--color-n-accent)" }}
        >
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
          </svg>
          View Hunter Security Audit Report ↗
        </a>
      </div>
    ),
  },
];

const DEPOSIT_STEPS = [
  {
    step: "1",
    title: "Connect your wallet",
    body: "Tap Connect Wallet and sign in with MetaMask, Coinbase Wallet, or any EVM-compatible wallet. No account or KYC required",
  },
  {
    step: "2",
    title: "Choose a vault",
    body: "Pick a vault based on your goal. yoUSD for stable yield, yoETH or yoBTC for crypto exposure with yield, yoEUR for euro-denominated savings",
  },
  {
    step: "3",
    title: "Enter an amount",
    body: "Type how much you want to deposit. A preview shows the shares you will receive, your estimated yearly earnings, and the current APY",
  },
  {
    step: "4",
    title: "Approve the token",
    body: "On your first deposit to a vault, you will be asked to approve the token. This is a one-time wallet signature that allows the vault contract to receive your funds",
  },
  {
    step: "5",
    title: "Confirm the deposit",
    body: "Sign the deposit transaction in your wallet. Once confirmed on Base, your vault shares appear in your Portfolio",
  },
];

export function FAQ() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <div className="space-y-8 pb-6">
      <div>
        <h2 className="text-lg font-bold mb-4" style={{ color: "var(--color-n-text)" }}>
          Frequently Asked Questions
        </h2>
        <div className="space-y-2">
          {ITEMS.map((item, i) => {
            const isOpen = open === i;
            return (
              <div
                key={i}
                className="rounded-2xl overflow-hidden transition-all"
                style={{
                  background: "var(--color-n-surface)",
                  border: `1px solid ${isOpen ? "var(--color-n-accent)" : "var(--color-n-border)"}`,
                }}
              >
                <button
                  className="w-full flex items-center justify-between px-5 py-4 text-left"
                  onClick={() => setOpen(isOpen ? null : i)}
                >
                  <span className="text-sm font-semibold pr-4" style={{ color: "var(--color-n-text)" }}>
                    {item.q}
                  </span>
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="var(--color-n-muted)"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    style={{
                      flexShrink: 0,
                      transition: "transform 0.2s ease",
                      transform: isOpen ? "rotate(180deg)" : "rotate(0deg)",
                    }}
                  >
                    <path d="m6 9 6 6 6-6" />
                  </svg>
                </button>
                {isOpen && (
                  <div className="px-5 pb-5">
                    <div
                      className="pt-3"
                      style={{ borderTop: "1px solid var(--color-n-border)" }}
                    >
                      {item.a}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      <div>
        <h2 className="text-lg font-bold mb-4" style={{ color: "var(--color-n-text)" }}>
          How to Deposit
        </h2>
        <div
          className="rounded-2xl overflow-hidden"
          style={{
            background: "var(--color-n-surface)",
            border: "1px solid var(--color-n-border)",
          }}
        >
          {DEPOSIT_STEPS.map(({ step, title, body }, i) => (
            <div
              key={step}
              className="flex gap-4 px-5 py-4"
              style={{
                borderBottom: i < DEPOSIT_STEPS.length - 1 ? "1px solid var(--color-n-border)" : "none",
              }}
            >
              <div
                className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold mt-0.5"
                style={{
                  background: "var(--color-n-accent-glow)",
                  color: "var(--color-n-accent)",
                }}
              >
                {step}
              </div>
              <div>
                <p className="text-sm font-semibold mb-1" style={{ color: "var(--color-n-text)" }}>
                  {title}
                </p>
                <p className="text-xs leading-relaxed" style={{ color: "var(--color-n-muted)" }}>
                  {body}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
